### ISSUE TITLE
[Feature]: config file and information about discord

### ISSUE THREAD

**Issue by McBlankenburg** [Progress-House/ofitoo-backend#30]
### As a 

Technical Team Member

### I would like to 

have information about discord of progress-house when somebody click in "new issue"

### requirements: 

something like that
![image](https://github.com/Progress-House/ofitoo-backend/assets/58309339/c4988ddf-1db3-4a80-8670-e5c9721cb282)

### docs / links / diagrams: 

```yaml
blank_issues_enabled: false
contact_links:
  - name: Need talk with us or join as contributor?
    url: https://discord.gg/rv5Z4jjXem
    about: Visit our discord channel.
```

https://github.com/testcontainers/testcontainers-go/issues/new/choose
https://github.com/testcontainers/testcontainers-go/blob/main/.github/ISSUE_TEMPLATE/config.yml
